[package]
name = "deduplines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
itertools = "0.12.1"
ordered-float = "4.2.0"

[dev-dependencies]
bitvec = "1.0.1"
rand = "0.8.5"
